### ISSUE TITLE
query_users API call doesn't use all available paramters

### ISSUE THREAD

**Issue by tivaliy** [avadev/AvaTax-REST-V2-Python-SDK#35]
SDK API call `query_users` claims about parameters in documentation (as well as in REST), but actually doesn't involve several of them:

https://github.com/avadev/AvaTax-REST-V2-Python-SDK/blob/master/src/client_methods.py#L6426-L6447

**Comment by han8909227** [comment]
Hi @tivaliy 
So all of our parameter with `$` in front are query string parameters (optional too), in this SDK they can be set through the `include` function parameter in each call function. 
For an example, `my_client.query_user(include={'$include': 'myInclude', '$orderBy': 'id ASC'}`

Perhaps the name include is misleading since there is a `$include` query string param in AvaTax, I will probably changing that variable to `payload` in a future release
